In [1]:
from absenteeism_module import *

In [2]:
new_data = pd.read_csv('Absenteeism_new_data.csv')
new_data.head()

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets
0,22,27,01/06/2018,179,26,30,237.656,19,3,0,0
1,10,7,04/06/2018,361,52,28,237.656,27,1,1,4
2,14,23,06/06/2018,155,12,34,237.656,25,1,2,0
3,17,25,08/06/2018,179,22,40,237.656,22,2,2,0
4,14,10,08/06/2018,155,12,34,237.656,25,1,2,0

In [3]:
model = absenteeism_model('model','scaler')

In [4]:
model.load_and_clean_data('Absenteeism_new_data.csv')

In [5]:
model.predicted_outputs()

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Probability,Prediction
0,False,0.0,False,True,6,179,30,19,1,0,0,0.140338,0
1,True,0.0,False,False,6,361,28,27,0,1,4,0.887683,1
2,False,0.0,False,True,6,155,34,25,0,2,0,0.291081,0
3,False,0.0,False,True,6,179,40,22,1,2,0,0.212371,0
4,True,0.0,False,False,6,155,34,25,0,2,0,0.742481,1
5,True,0.0,False,False,6,225,28,24,0,1,2,0.742514,1
6,True,0.0,False,False,6,118,46,25,0,2,0,0.555419,1
7,False,0.0,False,True,6,179,30,19,1,0,0,0.140338,0
8,False,0.0,False,True,6,118,37,28,0,0,0,0.128860,0
9,True,0.0,False,False,6,118,37,28,0,0,0,0.509490,1
10,False,0.0,False,True,6,378,36,21,0,2,4,0.493012,0
11,False,0.0,True,False,6,118,50,31,0,1,0,0.562050,1
12,False,0.0,True,False,6,233,31,21,1,1,8,0.325329,0
13,False,0.0,False,True,6,179,30,19,1,0,0,0.140338,0
14,False,0.0,False,False,6,235,48,33,0,1,5,0.059105,0
15,False,0.0,False,False,6,268,33,25,1,0,0,0.159146,0
16,False,0.0,True,False,6,118,50,31,0,1,0,0.562050,1
17,True,0.0,False,False,6,179,30,19,1,0,0,0.534086,1
18,False,0.0,False,True,6,291,40,25,0,1,1,0.400604,0
19,True,0.0,False,False,7,179,30,19,1,0,0,0.539363,1
20,False,0.0,False,True,7,118,37,28,0,0,0,0.131261,0
21,False,0.0,False,True,7,233,31,21,1,1,8,0.054990,0
22,True,0.0,False,False,7,118,37,28,0,0,0,0.514793,1
23,True,0.0,False,False,7,118,37,28,0,0,0,0.514793,1
24,False,0.0,False,True,7,233,31,21,1,1,8,0.054990,0
25,False,0.0,False,True,7,235,43,38,0,1,0,0.493870,0
26,False,0.0,True,False,7,233,31,21,1,1,8,0.330005,0
27,True,0.0,False,False,7,228,58,22,0,2,1,0.603430,1
28,False,0.0,False,True,7,118,37,28,0,0,0,0.131261,0
29,True,0.0,False,False,7,228,58,22,0,2,1,0.603430,1
30,False,0.0,False,True,7,189,33,25,0,2,2,0.268745,0
31,False,0.0,False,True,7,118,37,28,0,0,0,0.131261,0
32,False,0.0,False,True,7,361,28,27,0,1,4,0.534811,1
33,False,0.0,False,True,7,225,28,24,0,1,2,0.295517,0
34,True,0.0,False,False,7,369,31,25,0,3,0,0.974870,1
35,True,0.0,False,False,7,289,33,30,0,2,1,0.922702,1
36,True,0.0,False,False,7,235,37,29,1,1,1,0.756235,1
37,False,0.0,False,False,7,118,40,34,0,1,8,0.013679,0
38,False,0.0,False,False,7,231,39,35,0,2,2,0.232350,0
39,False,0.0,False,False,7,179,53,25,0,1,1,0.049359,0

# The probability column describes the chance that a given individual is expected to be significantly absent from work
# for more than 3 hours (excessively absent)

# Similarly, prediction column displays the model's prediction
## 1 - probability was >= 50% 
## 0 - probability was < 50%

### Now to save the new table as a csv

In [6]:
model.predicted_outputs().to_csv('Absenteeism_predictions.csv', index = False)